fix: Moved the seed create wait to a new target to improve CI scripting
rh-ecosystem-edge/ib-orchestrate-vm pull request #23
Opened 2024-01-17 15:03 UTC by jeff-roche

2024-01-17 15:09 UTC, javipolo requested changes

2024-01-17 15:09 UTC, javipolo commented on Makefile
> +		sleep 5m; \
Use shorter time for sleep, or at least make it so it can be configured with a variable

2024-01-17 15:09 UTC, javipolo commented on Makefile
> +wait-seed-image-create:
Add also the CLUSTER=blahblah so the target can be called easily

2024-01-26 16:16 UTC, jeff-roche commented
@javipolo is this good to merge?

2024-01-30 14:00 UTC, merged